apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    nodePort: 30200
  - name: transport
    port: 9300
    nodePort: 30300
